name: Build binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on:  macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Set Tcl/Tk path
      run: |
          version=$(brew info tcl-tk --json | jq -r '.[].installed[].version')
          ln -s /usr/local/Cellar/tcl-tk/$version/lib/libtcl8.6.dylib /usr/local/lib/libtcl8.6.dylib
          ln -s /usr/local/Cellar/tcl-tk/$version/lib/libtk8.6.dylib /usr/local/lib/libtk8.6.dylib
    - name: install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    
    - name: lock package version
      run: pipenv lock
    
    - name: install packages
      run: pipenv sync --dev
        
    - name: Install nuitka
      run: |
        pip install nuitka
        
    - name: Build with nuitka
      run: python -m nuitka --assume-yes-for-downloads --standalone --enable-plugin=tk-inter --enable-plugin=numpy imgs2xl/gui.py
        
    - name: check outputs
      run: |
        ls -lR ./dist
        ls -lR ./build
