name: Build binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on:  macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Set Tcl/Tk path
      run: |
          version=$(brew info tcl-tk --json | jq -r '.[].installed[].version')
          echo "PATH=/usr/local/Cellar/tcl-tk/$version/bin:$PATH" > $GITHUB_ENV
          echo "LDFLAGS=-L/usr/local/Cellar/tcl-tk/$version/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/Cellar/tcl-tk/$version/include" >> $GITHUB_ENV
          echo "TCL_LIBRARY=/usr/local/Cellar/tcl-tk/$version" >> $GITHUB_ENV
          echo "TK_LIBRARY=/usr/local/Cellar/tcl-tk/$version" >> $GITHUB_ENV
    - name: install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    
    - name: lock package version
      run: pipenv lock
    
    - name: install packages
      run: pipenv sync --dev
        
    - name: Install nuitka
      run: |
        pip install nuitka
        
    - name: Build with nuitka
      run: |
        python -m nuitka --assume-yes-for-downloads --standalone --enable-plugin=tk-inter --enable-plugin=numpy imgs2xl/gui.py
        tar cvfz gui.dist.tgz gui.dist/*
        
    - name: save dist
      uses: actions/upload-artifact@v2
      with:
        name: gui.dist.tgz
        path: ./gui.dist.tgz
